### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by keller-mark**
I wanted to mention Cistrome DB toolkit in the description and add a link to the fork of the HiGlass Server repository I made today. In the Dropbox document I shared in the #development higlass slack Pete recommended that we make a fork where we can make our changes and later we can merge them with the main HiGlass Server repository.

### CODE REVIEW

**Comment by sehilyi** [comment]
Looks good. I will merge this.

**Comment by sehilyi** [comment]
@keller-mark Could you ping me when the aggregation part from the server side is ready so that I can test in the client side? 

And, can you assign me as a reviewer when you make large updates to the fork so that I can take a look and learn? :)

**Comment by keller-mark** [comment]
Yes the server side aggregation is working.

These are the changes to the HiGlass core and to the HiGlass Server that I made:

- https://github.com/higlass/higlass/compare/keller-mark/aggregation-post-api
- https://github.com/higlass/higlass-server/compare/develop...hms-dbmi:keller-mark/aggregation-post-api

I will also take time to write some instructions for how to test it out and share with you as soon as I do that

**Comment by keller-mark** [comment]
In the view config the aggregation information looks the same except for a new option
`"selectRowsAggregationMethod": "server"` (by default it will be `"client"`)

```
    "selectRows": [
        [216, 71, 206, 121],
        [192, 190, 191, 41, 42, 43]
    ],
    "selectRowsAggregationMode": "sum",
    "selectRowsAggregationWithRelativeHeight": true,
    "selectRowsAggregationMethod": "server",
```

**Comment by sehilyi** [comment]
Thanks for sharing!

**Pull request merged**
